name: vitalink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_messaging: ^15.2.9
  brasil_fields: ^1.15.0
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^12.0.0
  geolocator_android: 4.5.5
  http: ^1.2.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  lucide_icons: ^0.257.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  skeletonizer: ^1.4.2
  sqflite: ^2.3.3+1
  svg_flutter: ^0.0.1
  url_launcher: ^6.3.0
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Black.ttf
        - asset: fonts/inter/Inter-Bold.ttf
        - asset: fonts/inter/Inter-ExtraBold.ttf
        - asset: fonts/inter/Inter-ExtraLight.ttf
        - asset: fonts/inter/Inter-Light.ttf
        - asset: fonts/inter/Inter-Medium.ttf
        - asset: fonts/inter/Inter-Regular.ttf
        - asset: fonts/inter/Inter-SemiBold.ttf
        - asset: fonts/inter/Inter-Thin.ttf

  generate: true

  assets:
    - assets/images/